version: 2
jobs:
  build:
    docker:
      - image: node:7.10.0
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn
      - run: yarn test:e2e
      - run: yarn test:cov
      - run: yarn format:check